name: lighthouseci
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.github/**"

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: CI=false npm run build
      - run: lhci collect --additive --configPath=./github/lhconfig/desktop-lighthouserc.js
      - run: lhci collect --additive --configPath=./github/lhconfig/mobile-lighthouserc.js
      - run: lhci assert
      - run: lhci upload
